greetings:
  - Welcome aboard! ğŸš€
  - Hello there, newcomer! ğŸ‘‹
  - Hey, fantastic to see you here! ğŸŒŸ
  - Greetings, explorer of our code universe! ğŸŒ
  - Ahoy there! Ready to embark on a coding adventure? âš“

